CREATE TABLE profiles.profile
(
    profile_id    BIGINT                                   NOT NULL,
    login_id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    icon          SMALLINT,
    creation_date TIMESTAMP with time zone                 NOT NULL,
    CONSTRAINT pk_profile PRIMARY KEY (profile_id)
);

CREATE TABLE security.login
(
    login_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                             NOT NULL,
    email    VARCHAR(255)                             NOT NULL,
    password VARCHAR(255)                             NOT NULL,
    enabled  BOOLEAN,
    CONSTRAINT pk_login PRIMARY KEY (login_id)
);

CREATE TABLE security.login_roles
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    login_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id  BIGINT                                   NOT NULL,
    CONSTRAINT pk_login_roles PRIMARY KEY (id)
);

CREATE TABLE security.role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE security.verification_tokens
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token                 VARCHAR(255)                            NOT NULL,
    unverified_user_email VARCHAR(255)                            NOT NULL,
    expiry_date           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_verificationtokens PRIMARY KEY (id)
);

ALTER TABLE security.login
    ADD CONSTRAINT uc_4f7d168134e849c7369f3a19b UNIQUE (email);

ALTER TABLE security.login
    ADD CONSTRAINT uc_ad38feae6fe8930ce2d49dd68 UNIQUE (username);

ALTER TABLE security.verification_tokens
    ADD CONSTRAINT uc_verificationtokens_token UNIQUE (token);

ALTER TABLE security.verification_tokens
    ADD CONSTRAINT uc_verificationtokens_unverifieduseremail UNIQUE (unverified_user_email);

ALTER TABLE profiles.profile
    ADD CONSTRAINT FK_PROFILE_ON_LOGINID FOREIGN KEY (login_id) REFERENCES security.login (login_id);

ALTER TABLE security.login_roles
    ADD CONSTRAINT FK_LOGIN_ROLES_ON_LOGIN FOREIGN KEY (login_id) REFERENCES security.login (login_id);

ALTER TABLE security.login_roles
    ADD CONSTRAINT FK_LOGIN_ROLES_ON_ROLE FOREIGN KEY (role_id) REFERENCES security.role (id);